import { test, expect, vi } from 'vitest';
import { fixture } from './fixtures';
import { capture, synchronize, statuses, keepSummary, keepSummaries, forkBranch } from './canonical';
import { eventView, editEvent, wrapEvents } from './events';
import { commitManualEvent, keepEventOverview, updateEventOverview, eventPending } from './manual-events';
import { exportLibrary, restoreLibrary, validateData } from './migration';
import { STORES, type MemoryRevision } from './model';
const response = JSON.stringify({ title: '合成事件', status: 'open', keywords: [], overview: '已经整理好的关系变化', progress: '最初进展' });
const budget = { chains: 2, excerptChars: 500, totalChars: 1600, extra: 1 };
test('91 high summaries and 15 events survive an unused final edit, delete and regenerated reply', async () => {
  const { lib, input, branch } = await fixture(3);
  for (let i = 6; i < 561; i++) input.messages.push({ key: `tail-${i}`, role: i % 2 ? 'assistant' : 'user', content: `合成未总结正文 ${i}`, swipe: 0 });
  for (let i = 0; i < 91; i++) input.memories.push({ ...input.memories[0], hostId: `high-${i}`, level: 1, anchorKey: null, children: ['leaf-0'], content: `合成高层摘要 ${i}` });
  await synchronize(lib, input);
  for (let i = 0; i < 15; i++) { const v = await capture(lib, branch.id); await commitManualEvent(lib, v, null, [v.memories[0].id], response, () => true); }
  const before = await lib.all('event_revisions');
  for (const change of [() => { input.messages[560].content += '改错字'; }, () => { input.messages.pop(); }, () => { input.messages.push({ key: 'regenerated-tail', role: 'assistant', content: '新的回复', swipe: 0 }); }]) {
    change(); await synchronize(lib, input);
    const view = await capture(lib, branch.id), validity = await statuses(lib, view), cards = (await eventView(lib, view)).cards;
    expect([...validity.values()].every(s => s === 'valid')).toBe(true);
    expect(cards).toHaveLength(15); expect(cards.every(c => !eventPending(c) && c.meta.overview === '已经整理好的关系变化')).toBe(true);
    expect(await lib.all('event_revisions')).toEqual(before);
  }
  lib.close();
});
test('bulk retain records exact sources, survives unrelated tail changes, rejects new relevant edits and roundtrips v7', async () => {
  const { lib, input, view: original, branch } = await fixture(2);
  input.memories[0].inputRefs = original.refs.slice(0,2); input.memories[0].coverage = original.refs.slice(0,2);
  input.memories.push({ ...input.memories[1], hostId: 'high', level: 1, anchorKey: null, children: ['leaf-0'], inputRefs: [], coverage: [] });
  await synchronize(lib, input);
  let view = await capture(lib, branch.id);
  const old = view.memories[0];
  const id = await commitManualEvent(lib, view, null, [old.id], response, () => true);
  input.messages[1].content += '小修正'; await synchronize(lib, input); view = await capture(lib, branch.id);
  const cards = (await eventView(lib, view)).cards;
  expect(cards[0]).toMatchObject({ needsReview: true, blocked: true });
  expect(wrapEvents(cards, view, [old.id], [], budget)).toBe('');
  const pending = await statuses(lib, view);
  await keepSummaries(lib, view, view.memories.filter(m => pending.get(m.id) !== 'valid').map(m => m.id));
  view = await capture(lib, branch.id);
  expect([...await statuses(lib, view)].every(([,s]) => s === 'valid')).toBe(true);
  expect(eventPending((await eventView(lib, view)).cards[0])).toBe(false);
  input.messages.push({ key: 'append', role: 'user', content: '新消息', swipe: 0 }); await synchronize(lib, input);
  view = await capture(lib, branch.id);
  expect((await statuses(lib, view)).get(old.id)).toBe('valid');
  expect(await lib.get('memory_revisions', old.id)).toEqual(old);
  const pack = await exportLibrary(lib); expect(pack.version).toBe(7);
  const restored = await restoreLibrary(pack, false);
  expect((await eventView(restored, await capture(restored, branch.id))).cards[0].chain.id).toBe(id);
  expect((await exportLibrary(restored)).data).toEqual(pack.data); restored.close();
  const tampered = structuredClone(pack), review = tampered.data.reviews.find((r:any) => r.sourceRefs.length) as any;
  review.sourceRefs = []; expect(() => validateData(tampered)).toThrow('审核来源身份');
  input.messages[1].content += '再次改动'; await synchronize(lib, input);
  expect((await statuses(lib, await capture(lib, branch.id))).get(old.id)).toBe('needs_review');
  lib.close();
});
test('manual summary versions keep event membership; high summary and overview can be confirmed independently', async () => {
  const { lib, input, branch, view: base } = await fixture(1);
  input.memories[0].inputRefs = base.refs; input.memories[0].coverage = base.refs;
  input.memories.push({ ...input.memories[0], hostId: 'high', level: 1, anchorKey: null, children: ['leaf-0'], inputRefs: [], coverage: [] });
  await synchronize(lib, input); let view = await capture(lib, branch.id);
  const original = view.memories[0], high = view.memories[1];
  const id = await commitManualEvent(lib, view, null, [original.id], response, () => true);
  const { inputRefs, coverage, ...manual } = input.memories[0];
  input.memories[0] = { ...manual, content: '补上遗漏细节', manualEdit: true, generationKey: 2 };
  await synchronize(lib, input); view = await capture(lib, branch.id);
  const next = view.memories[0];
  expect(next.id).not.toBe(original.id); expect(next.inputRefs).toEqual(original.inputRefs);
  expect((await statuses(lib, view)).get(next.id)).toBe('valid');
  expect((await statuses(lib, view)).get(high.id)).toBe('needs_rebuild');
  let card = (await eventView(lib, view)).cards[0];
  expect(card.members.map(m => m.memory)).toEqual([next.id]); expect(card.needsReview).toBe(true); expect(card.blocked).toBe(false);
  await keepEventOverview(lib, view, id); view = await capture(lib, branch.id);
  expect(eventPending((await eventView(lib, view)).cards[0])).toBe(false);
  expect((await statuses(lib, view)).get(high.id)).toBe('needs_rebuild');
  await keepSummary(lib, view, high.id); view = await capture(lib, branch.id);
  expect((await statuses(lib, view)).get(high.id)).toBe('valid');
  input.memories[0].content += '又补充'; input.memories[0].generationKey = 3;
  await synchronize(lib, input); view = await capture(lib, branch.id); card = (await eventView(lib, view)).cards[0];
  const sender = vi.fn(async () => response);
  await updateEventOverview(lib, view, id, 48000, sender); expect(sender).toHaveBeenCalledTimes(1);
  view = await capture(lib, branch.id); card = (await eventView(lib, view)).cards[0];
  expect(eventPending(card)).toBe(false); expect(await lib.all('event_progress')).toHaveLength(1);
  expect(await lib.get('memory_revisions', original.id)).toEqual(original);
  expect(wrapEvents([card], view, [view.memories[0].id], [], budget)).toContain(card.meta.overview);
  validateData(await exportLibrary(lib)); lib.close();
});
test('deleted sources remain visible locally, cannot be confirmed or sent; unlink resolves without erasing history', async () => {
  const { lib, input, branch, view } = await fixture(1);
  const id = await commitManualEvent(lib, view, null, [view.memories[0].id], response, () => true);
  input.messages.pop(); input.memories = []; await synchronize(lib, input);
  let current = await capture(lib, branch.id), card = (await eventView(lib, current)).cards[0];
  expect(card.blocked).toBe(true); expect(card.memberDetails?.[0].content).toBe(view.memories[0].content);
  const sender = vi.fn(async () => response);
  await expect(updateEventOverview(lib, current, id, 48000, sender)).rejects.toThrow('来源'); expect(sender).not.toHaveBeenCalled();
  await expect(keepEventOverview(lib, current, id)).rejects.toThrow('来源');
  await editEvent(lib, current, id, card.meta, { memory: view.memories[0].id, active: false, kind: 'progress' });
  current = await capture(lib, branch.id); await keepEventOverview(lib, current, id);
  expect((await eventView(lib, await capture(lib, branch.id))).cards[0].members).toEqual([]);
  expect(await lib.get('memory_revisions', view.memories[0].id)).toBeDefined();
  lib.close();
});
test('review rejects changed host and reordered identities; current event UI never leaks into historical cutoff or child branch', async () => {
  const { lib, input, branch, view } = await fixture(2);
  const id = await commitManualEvent(lib, view, null, [view.memories[1].id], response, () => true);
  let current = await capture(lib, branch.id);
  const counts = await Promise.all(STORES.map(s => lib.all(s).then(r => r.length)));
  await expect(keepSummary(lib, current, view.memories[1].id, () => false)).rejects.toThrow('视图');
  expect(await Promise.all(STORES.map(s => lib.all(s).then(r => r.length)))).toEqual(counts);
  expect((await eventView(lib, await capture(lib, branch.id, 2))).cards).toEqual([]);
  const child = await forkBranch(lib, current, 'explicit-child'); expect((await eventView(lib, await capture(lib, child.id))).cards).toEqual([]);
  [input.messages[0], input.messages[1]] = [input.messages[1], input.messages[0]]; await synchronize(lib, input); current = await capture(lib, branch.id);
  await expect(keepSummary(lib, current, view.memories[1].id)).rejects.toThrow('重排');
  expect((await eventView(lib, current)).cards[0].chain.id).toBe(id); lib.close();
});
