import 'fake-indexeddb/auto';
import { beforeEach, afterEach, test, expect, vi } from 'vitest';
import { fixture } from './fixtures';
import * as bridge from './bridge';
import * as db from './db';
import * as settings from '@/api/settings';
import * as context from '@/st/context';
import * as engine from '@/memory/engine';
import * as indexing from '@/memory/vector/index';
import * as scope from '@/memory/vector/scope';
import * as vector from '@/memory/vector/store';
import * as embed from '@/memory/vector/embed';
import * as rewrite from '@/memory/vector/rewrite';
import * as lexical from '@/memory/vector/bm25';
import * as knowledge from '@/memory/vector/knowledge';
import { clearRecallInjection, runVectorRecall } from '@/memory/vector/recall';
import { recallDebug } from '@/memory/vector/debug';
import { capture } from './canonical';
import { editEvent } from './events';
let lib: db.Library, view: Awaited<ReturnType<typeof fixture>>['view'], leaves: bridge.CanonicalLeaf[], inject: ReturnType<typeof vi.fn>, host = 'stable';
const original = JSON.parse(JSON.stringify(settings.apiSettings.vector));
beforeEach(async () => {
    const f = await fixture(4);
    lib = f.lib;
    view = f.view;
    host = 'stable';
    inject = vi.fn();
    vi.stubGlobal('localStorage', { getItem: () => null, setItem: () => { } });
    Object.assign(settings.apiSettings.vector, { enabled: true, knowledge: { enabled: false, count: 1, threshold: .8, maxChars: 2000 } });
    Object.assign(settings.apiSettings.vector.recall, { minAiFloors: 0, rerankCandidates: 10, bm25Candidates: 10, fusionCandidates: 10, bm25Count: 1, rrfCount: 1, fullTextCount: 1, finalRecallCount: 3, embeddingThreshold: .8, rerankThreshold: .9 });
    vi.spyOn(settings, 'engineActiveHere').mockReturnValue(true);
    vi.spyOn(db, 'activeLibrary').mockResolvedValue(lib);
    vi.spyOn(bridge, 'dailyInstalled').mockReturnValue(true);
    vi.spyOn(bridge, 'syncDaily').mockImplementation(async () => view);
    vi.spyOn(bridge, 'hostVersion').mockImplementation(() => host);
    leaves = view.memories.map((m, i) => ({ leafId: m.id, hostId: m.hostId, docHash: m.fingerprint, payloadHash: m.fingerprint, document: m.content, mesFull: f.input.messages[i * 2 + 1].content, storyTime: '', msgIndex: i * 2 + 1 }));
    vi.spyOn(bridge, 'canonicalLeaves').mockImplementation(() => leaves);
    vi.spyOn(context, 'getContext').mockReturnValue({ chat: [{ is_user: false, mes: '近期全文' }, { is_user: true, mes: '玉佩' }], setExtensionPrompt: inject } as any);
    vi.spyOn(scope, 'currentVectorDb').mockReturnValue('synthetic-db');
    vi.spyOn(scope, 'currentChatId').mockReturnValue('synthetic');
    vi.spyOn(scope, 'currentChatScope').mockReturnValue('chat:synthetic');
    vi.spyOn(scope, 'recallScopes').mockReturnValue(['chat:synthetic', 'bundle:foreign']);
    vi.spyOn(scope, 'currentBundleHashes').mockReturnValue([]);
    vi.spyOn(engine, 'resolveKeepStart').mockReturnValue(1);
    vi.spyOn(indexing, 'ensureRecallIndex').mockResolvedValue(undefined);
    vi.spyOn(indexing, 'collectLeaves').mockImplementation(() => leaves);
    vi.spyOn(embed, 'embedTexts').mockResolvedValue([new Float32Array([1, 0])]);
    vi.spyOn(rewrite, 'rewriteQuery').mockResolvedValue({ intent: '合成召回', queries: ['玉佩'] });
    vi.spyOn(vector, 'vecSearch').mockImplementation(async () => ({ results: leaves.map(l => ({ ...l, scope: 'chat:synthetic', similarity: .85, queryIndex: 0 })) }));
    vi.spyOn(lexical, 'searchBm25').mockImplementation(async () => ({ hits: leaves.map((l, i) => ({ id: l.leafId, score: 10 - i })), persistent: false }) as any);
    vi.spyOn(embed, 'rerankDocuments').mockResolvedValue([{ index: 0, score: .99 }]);
    clearRecallInjection();
    inject.mockClear();
});
afterEach(() => { lib.close(); Object.assign(settings.apiSettings.vector, original); vi.restoreAllMocks(); vi.unstubAllGlobals(); });
const text = () => String(inject.mock.calls.at(-1)?.[1] ?? '');
test('adapter keeps native ranking and quotas but upgrades full text from canonical payload', async () => {
    vi.mocked(vector.vecSearch).mockResolvedValue({ results: leaves.map(l => ({ ...l, mesFull: 'STALE_BACKEND_BODY', document: 'STALE_BACKEND_SUMMARY', scope: 'chat:synthetic', similarity: .85, queryIndex: 0 })) });
    await runVectorRecall();
    expect(text()).toContain(leaves[0].mesFull);
    expect(text()).toContain(leaves[1].document);
    expect(text()).toContain(leaves[2].document);
    expect(text()).not.toContain('STALE_BACKEND');
    expect(inject.mock.calls.at(-1)?.[0]).toBe('mnemosyne_vector_recall');
});
test('foreign scopes and unknown revisions are removed before rerank, preserving valid candidates', async () => {
    vi.mocked(vector.vecSearch).mockResolvedValue({ results: [{ ...leaves[0], leafId: 'foreign', mesFull: 'FOREIGN_BODY', scope: 'bundle:foreign', similarity: 1, queryIndex:0 },
            { ...leaves[0], mesFull: 'WRONG_SCOPE', scope: 'chat:other', similarity: 1, queryIndex:0 }, { ...leaves[0], scope: 'chat:synthetic', similarity: .85, queryIndex:0 }] });
    await runVectorRecall();
    const docs = vi.mocked(embed.rerankDocuments).mock.calls[0][1];
    expect(docs.join()).not.toContain('FOREIGN');
    expect(docs.join()).not.toContain('WRONG_SCOPE');
    expect(text()).toContain(leaves[0].mesFull);
});
test('late rerank result after host edit is never injected', async () => {
    vi.mocked(embed.rerankDocuments).mockImplementation(async () => { host = 'changed'; return [{ index: 0, score: .99 }]; });
    await runVectorRecall();
    expect(text()).toBe('');
});
test('an event edit during rerank advances DB epoch and blocks obsolete recall publication', async () => {
    vi.mocked(embed.rerankDocuments).mockImplementation(async () => { await editEvent(lib, view, null, { title: '人工变化', status: 'open', keywords: [] }); return [{ index: 0, score: .99 }]; });
    await runVectorRecall();
    expect(text()).toBe('');
});
test('canonical unavailable still permits independently budgeted knowledge recall', async () => {
    vi.mocked(bridge.syncDaily).mockRejectedValue(new Error('canonical blocked'));
    leaves = [];
    settings.apiSettings.vector.knowledge.enabled = true;
    vi.spyOn(knowledge, 'listKnowledge').mockResolvedValue([{ id: 'knowledge', database: 'synthetic-db', name: '合成知识', delimiter: '---', chunks: ['独立知识'], enabled: true, embedding: knowledge.embeddingIdentity(), revision: '1' }]);
    vi.spyOn(knowledge, 'recallKnowledge').mockResolvedValue('独立知识，额度未受摘要阻塞影响');
    await runVectorRecall();
    expect(text()).toContain('独立知识');
    expect(vector.vecSearch).not.toHaveBeenCalled();
    expect(indexing.ensureRecallIndex).not.toHaveBeenCalled();
});
test('rerank fallback uses cosine for legacy tier behavior while reporting no fabricated rerank score', async () => {
    settings.apiSettings.vector.recall.rerankThreshold = .8;
    vi.mocked(embed.rerankDocuments).mockRejectedValue(new Error('unavailable'));
    await runVectorRecall();
    expect(text()).toContain(leaves[0].mesFull);
    expect(recallDebug.rerank.every((h: any) => h.rerankScore === null)).toBe(true);
});
