export const styles=`
:host{all:initial;position:fixed!important;inset:0!important;width:0!important;height:0!important;min-width:0!important;min-height:0!important;pointer-events:none;z-index:2147483000;font-family:Inter,"Segoe UI","Microsoft YaHei",sans-serif;color-scheme:light dark;--bg:#f6f5f1;--card:#fff;--ink:#243b3b;--muted:#657776;--line:#dae3de;--accent:#22695f;--soft:#e5f0e9;--shadow:0 18px 65px #132f3430;font-size:14px;line-height:1.55}
*{box-sizing:border-box} [hidden]{display:none!important}
button,input,select{font:inherit}button{cursor:pointer}button:disabled{cursor:default;opacity:.45}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #cf9c53;outline-offset:2px}
.panel{pointer-events:auto;position:fixed;right:28px;bottom:92px;width:620px;height:690px;max-width:calc(100vw - 16px);max-height:calc(100dvh - 24px);min-width:300px;min-height:320px;z-index:2147483001;display:flex;flex-direction:column;background:var(--bg);color:var(--ink);border:1px solid var(--line);border-radius:20px;box-shadow:var(--shadow);overflow:hidden}
.panel[data-theme=dark]{color-scheme:dark;--bg:#172426;--card:#203134;--ink:#e4efea;--muted:#a3b8b2;--line:#3a5051;--accent:#96d7bd;--soft:#2b4742;--shadow:0 18px 65px #0007}
header{display:flex;align-items:center;gap:10px;padding:18px 20px 13px;border-bottom:1px solid var(--line);touch-action:none;cursor:move;user-select:none;background:var(--card)}
.brand{flex:1;font-weight:650;font-size:18px;letter-spacing:.02em}.brand small{display:block;font-size:10px;letter-spacing:.15em;color:var(--muted);font-weight:500}.icon{border:0;background:var(--soft);color:var(--ink);border-radius:9px;padding:6px 10px}
main{overflow:auto;flex:1;padding:18px 20px 24px;scrollbar-width:thin}.row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.row>select,.grow{flex:1;min-width:100px}.section{margin-bottom:14px}.label{display:block;font-size:12px;color:var(--muted);margin-bottom:6px;font-weight:600}input,select{background:var(--card);color:var(--ink);border:1px solid var(--line);border-radius:10px;padding:9px 11px;min-width:0}select{max-width:100%}input[type=checkbox]{accent-color:var(--accent);width:16px;height:16px}
.action{border:1px solid var(--line);border-radius:10px;padding:9px 13px;background:var(--card);color:var(--ink);white-space:nowrap}.primary{background:var(--accent);color:var(--bg);border-color:transparent;font-weight:650}.muted{font-size:12px;color:var(--muted)}.notice{background:var(--soft);border-radius:12px;padding:11px 13px;font-size:13px;white-space:pre-wrap;overflow-wrap:anywhere;margin:12px 0}.notice.error{border:1px solid #be776a}.check{display:flex;align-items:center;gap:5px;font-size:12px;color:var(--muted)}.search{margin-top:16px}.search input{width:0;flex:1}.filters{margin-top:9px}.filters select{font-size:12px}
.results{display:grid;gap:10px;margin-top:14px}.result{text-align:left;width:100%;border:1px solid var(--line);border-radius:13px;background:var(--card);padding:13px 15px;color:var(--ink)}.result:hover{border-color:var(--accent);box-shadow:0 3px 12px #133b2910}.meta{display:block;font-size:11px;color:var(--accent);font-weight:600;margin-bottom:5px;letter-spacing:.025em}.snippet{display:-webkit-box;-webkit-line-clamp:4;-webkit-box-orient:vertical;overflow:hidden;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.65}.empty{text-align:center;color:var(--muted);padding:24px 8px;font-size:13px}.detail{border:1px solid var(--line);border-radius:13px;background:var(--card);margin-top:14px;padding:14px}.detail pre{font:inherit;font-size:13px;line-height:1.75;white-space:pre-wrap;overflow-wrap:anywhere;margin:5px 0 17px}.detail h3{font-size:13px;color:var(--accent);margin:0 0 8px}.footer{padding:10px 44px 10px 20px;border-top:1px solid var(--line);font-size:11px;color:var(--muted);background:var(--card)}.grip{position:absolute;right:0;bottom:0;width:35px;height:35px;border:0;border-radius:14px 0 18px 0;background:linear-gradient(135deg,var(--soft),#bf965c66);color:var(--accent);font-size:23px;cursor:nwse-resize;touch-action:none}.preview{border:1px solid #c49b64;padding:12px;border-radius:12px;background:var(--card);margin-bottom:12px;white-space:pre-wrap}.preview p{margin:0 0 10px;font-size:13px}
.dropdown{position:relative;flex:1;min-width:100px}.dropdown-trigger{width:100%;display:flex;align-items:center;justify-content:space-between;gap:10px;text-align:left;border:1px solid var(--line);border-radius:11px;padding:9px 11px;background:var(--card);color:var(--ink);overflow:hidden}.dropdown-trigger:after{content:'⌄';color:var(--accent);font-size:15px}.dropdown-trigger[aria-expanded=true]{border-color:var(--accent);box-shadow:0 0 0 2px var(--soft)}.dropdown-menu{position:absolute;top:calc(100% + 6px);left:0;right:0;z-index:10;max-height:210px;overflow:auto;padding:5px;border:1px solid var(--line);border-radius:13px;background:var(--card);box-shadow:0 10px 28px #102d3430}.dropdown-option{display:block;width:100%;text-align:left;white-space:normal;overflow-wrap:anywhere;padding:9px 10px;border:0;border-radius:8px;color:var(--ink);background:transparent}.dropdown-option:hover,.dropdown-option:focus-visible{background:var(--soft);outline:none}.dropdown-option[aria-selected=true]{background:var(--soft);color:var(--accent);font-weight:650}.filters .dropdown{flex:0 1 270px;font-size:12px}
@media(max-width:500px){.panel{right:8px;bottom:75px;width:calc(100vw - 16px);height:75dvh;min-width:280px}main{padding:14px}header{padding:14px}.action{padding:9px 10px}}
`;
